# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: ToDoList
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZDQ1NDFmZGZhNDg2N2Y4OGYzNmMxYTkxMGRhZTkyZjNmMmNiYWRhMGU2ODQyZjM5NmZjMmE2ZmRlNzQwNDgzMmRkYjdmYjJjZDQzY2E1NmY1ZTcxNWFiY2ZjY2EyNzY5ZDc2YjZiMjFhNDE3ODhjYzFlMDVkZjlkMDBhYjM3YTc=
